/*
 ---------- MM CREATE TABLE SCRIPT ---------------
|                                                 |
| Name: GenGenaralTables.sql                      |
| Created: Akos Ujvary                            |
| Last modifie:  MS Creation   2022.10.01         |
|                Creation      2017.11.05         |
 -------------------------------------------------
*/

---------------------- ERROR --------------------------

DROP TABLE IF EXISTS LOG.LOADING_ERROR;
CREATE TABLE LOG.LOADING_ERROR
(  
    ERR_ID VARCHAR(10),
    PR_ID VARCHAR(10),
    ERR_TYPE VARCHAR(30),
    ERR_MSG VARCHAR(100),
    TABLE_SRC VARCHAR(50),
    NATURE_KEY VARCHAR(50),
    NATURE_KEY_VALUE VARCHAR(1500),
    FAILED_COLUMN VARCHAR(150),
    FAILED_COLUMN_VALUE VARCHAR(MAX),
    RUN_DTTM DATETIME
);

DROP TABLE IF EXISTS LOG.PROCESS;
CREATE TABLE LOG.PROCESS
(  
    PR_ID VARCHAR(10),
    STEP_ID INTEGER,
    NAME VARCHAR(50),
    TYPE VARCHAR(10),
    DETAIL_MSG VARCHAR(200),
    ADDITIONAL_VARIABLE_NAME_1 VARCHAR(50),
    ADDITIONAL_VARIABLE_VALUE_1 VARCHAR(200),
    ADDITIONAL_VARIABLE_NAME_2 VARCHAR(50),
    ADDITIONAL_VARIABLE_VALUE_2 VARCHAR(200),
    ADDITIONAL_VARIABLE_NAME_3 VARCHAR(50),
    ADDITIONAL_VARIABLE_VALUE_3 VARCHAR(200),
    RUN_DTTM DATETIME
);


DROP TABLE IF EXISTS CONTROL.BIAS_SETTING;
CREATE TABLE CONTROL.BIAS_SETTING
(  
    CB_TYPE VARCHAR(30),
    RATING_TYPE VARCHAR(30),
    MIN_RATING_SCORE NUMERIC(3),
    AVG_SCORE NUMERIC(3),
    AVG_MIN NUMERIC(3),
    AVG_MAX NUMERIC(3),
    RATING_RANK_MULTIPLIER FLOAT,
    YEAR_SCORE NUMERIC(3),
    VOTING_SCORE NUMERIC(3),
    AVG_VOTING_MIN_PCT NUMERIC(2),
    AVG_VOTING_MAX_PCT NUMERIC(2),
    GLOBAL_MULTIPLIER_COUNTRY NUMERIC(5,2),
    GLOBAL_MULTIPLIER_GLOBAL NUMERIC(5,2),
    THRESHOLD_RATING_COUNTRY NUMERIC(3),
    THRESHOLD_RATING_GLOBAL NUMERIC(3)

);

GO
truncate table CONTROL.BIAS_SETTING
INSERT INTO CONTROL.BIAS_SETTING VALUES('BASIC_1', 'IMDB', 50, 40, 5, 8, 1, 40, 130, 10, 20, 1,1,70,80);
INSERT INTO CONTROL.BIAS_SETTING VALUES('BASIC_1', 'META', 30, 25, 5, 8, 1, 40, 130, 10, 20,1,1,70,80);
INSERT INTO CONTROL.BIAS_SETTING VALUES('BASIC_1', 'TOM', 30, 25, 5, 8, 1, 40, 130, 10, 20, 1,1,70,80);
INSERT INTO CONTROL.BIAS_SETTING VALUES('BASIC_1', 'TOM_USER', 30, 25, 5, 8, 1, 40, 130, 10, 20, 1,1,70,80);


DROP TABLE IF EXISTS CONTROL.FEATURE_SCORE;
CREATE TABLE CONTROL.FEATURE_SCORE
(  
    RATING_TYPE VARCHAR(30),
    ACTOR_SCORE NUMERIC(5,2),
    DIRECTOR_SCORE NUMERIC(5,2),
    WRITER_SCORE NUMERIC(5,2),
    GENRE_SCORE NUMERIC(5,2),
    COUNTRY_SCORE NUMERIC(5,2),
    GLOBAL_MULTIPLIER NUMERIC(5,2)
);

GO 

INSERT INTO CONTROL.FEATURE_SCORE VALUES('BASIC_1', 4, 4, 3, 1, 0.5, 1);
 
 select * from control.BIAS_SETTING

------------------ End of code -------------------------

