-- UPDATING MOVIEDATA SCHEMA TABLES WITH FIXED HUN NAMES

-- BACKUP MD
declare @returnparam smallint;
exec @returnparam=control.backup_md @tp='L';
select @returnparam;

-- TESTING NAMES ON MD
SELECT * FROM CONTROL.V_FIXED_MOVIEDATA_HUN_NAMES

-- UPDATING MD
UPDATE
    MOVIEDATA.ACTOR
SET
    MOVIEDATA.ACTOR.ACTOR_NM = HUNNAMES.FULL_FIXED_NAME
FROM
    MOVIEDATA.ACTOR ACT
INNER JOIN
    CONTROL.V_FIXED_MOVIEDATA_HUN_NAMES HUNNAMES
ON 
    ACT.ACTOR_ID = HUNNAMES.ID
    AND HUNNAMES.TYPE='A';

UPDATE
    MOVIEDATA.DIRECTOR
SET
    MOVIEDATA.DIRECTOR.DIRECTOR_NM = HUNNAMES.FULL_FIXED_NAME
FROM
    MOVIEDATA.DIRECTOR DIR
INNER JOIN
    CONTROL.V_FIXED_MOVIEDATA_HUN_NAMES HUNNAMES
ON 
    DIR.DIRECTOR_ID = HUNNAMES.ID
    AND HUNNAMES.TYPE='D';

UPDATE
    MOVIEDATA.WRITER
SET
    MOVIEDATA.WRITER.WRITER_NM = HUNNAMES.FULL_FIXED_NAME
FROM
    MOVIEDATA.WRITER WRITER
INNER JOIN
    CONTROL.V_FIXED_MOVIEDATA_HUN_NAMES HUNNAMES
ON 
    WRITER.WRITER_ID = HUNNAMES.ID
    AND HUNNAMES.TYPE='W';


-- COMPARING
SELECT * FROM MOVIEDATA.ACTOR
    EXCEPT
SELECT * FROM BCKP.ACTOR_0401

SELECT * FROM MOVIEDATA.DIRECTOR
    EXCEPT
SELECT * FROM BCKP.DIRECTOR_0401

SELECT * FROM MOVIEDATA.WRITER
    EXCEPT
SELECT * FROM BCKP.WRITER_0401
