
/*
 --------- MM CREATE SEQUENCES SCRIPT ------------
|                                                 |
| Name: GenSeq.sql                                |
| Created: Akos Ujvary                            |
| Last modified: 2022.08.23  Creation             |
 -------------------------------------------------
*/

CREATE SEQUENCE LOG.SEQ_PROCESS_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE LOG.SEQ_ERROR_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE MOVIEDATA.SEQ_ACTOR_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE MOVIEDATA.SEQ_COUNTRY_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE MOVIEDATA.SEQ_DIRECTOR_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE MOVIEDATA.SEQ_GENRE_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE MOVIEDATA.SEQ_MOVIEFEATURE_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE MOVIEDATA.SEQ_MOVIE_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE MOVIEDATA.SEQ_WRITER_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE USERDATA.SEQ_RATING_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO
  
CREATE SEQUENCE USERDATA.SEQ_RECOMMENDATION_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE USERDATA.SEQ_USERFEATURE_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO

CREATE SEQUENCE USERDATA.SEQ_USER_ID  
    AS INTEGER  
    START WITH 1  
    INCREMENT BY 1;
GO
