
WITH 

N_KW AS (
SELECT KWF.MOVIE_ID, KWF.KEYWORD_ID, KEYWORD_NM FROM MOVIEDATA.KEYWORDFEATURE KWF
LEFT JOIN MOVIEDATA.KEYWORD KW ON KW.KEYWORD_ID=KWF.KEYWORD_ID 
),

RNK_KW AS (
 SELECT DISTINCT 
    KEYWORD_ID, 
    CAST(ROUND((100.0 /(COUNT(*) OVER (PARTITION BY KEYWORD_ID))),2)AS FLOAT)   AS SPEC_CNT  
 FROM N_KW  )
 

--SELECT * FROM RNK_KW  

SELECT  
    MAIN.MOVIE_ID as MAIN_MOV_ID, MAIN.KEYWORD_NM as MAIN_KW,
    NB1_MOV.MOVIE_ID as NB1_MOVIE, NB1_KWS.KEYWORD_ID  as NB1_KW, NB1_KWS.KEYWORD_NM AS NB1_KW_NAME,
    RNK.SPEC_CNT
        
FROM N_KW MAIN 
LEFT JOIN N_KW NB1_MOV
ON NB1_MOV.KEYWORD_ID=MAIN.KEYWORD_ID
LEFT JOIN N_KW NB1_KWS
ON NB1_MOV.MOVIE_ID=NB1_KWS.MOVIE_ID
LEFT JOIN RNK_KW RNK 
ON RNK.KEYWORD_ID =NB1_KWS.KEYWORD_ID 

WHERE 1=1
and MAIN.MOVIE_ID != NB1_MOV.MOVIE_ID
AND MAIN.KEYWORD_ID!=NB1_KWS.KEYWORD_ID

and MAIN.MOVIE_ID='MOV028394' -- Rush

 

